<a href="https://colab.research.google.com/github/1mofumofu1/project/blob/main/PDF_TO_EXCEL_By_Neuralearn_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
from PIL import Image
import cv2
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
#!pip install paddlepaddle-gpu==2.3.2 cudatoolkit==10.2

In [13]:
!pip install paddlepaddle-gpu==2.3.0.post110 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

Looking in links: https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html


# pdf2image

## Installation

In [14]:
!pip install pdf2image
!apt-get update
!apt-get install poppler-utils

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:6 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 119 kB in 1s (102 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
poppler-utils is already the newest version (22.02.0-2ubuntu0.3).
0 upgraded, 0 newly installed, 

## Conversion

In [ ]:
from pdf2image import convert_from_path

In [ ]:
images = convert_from_path('/content/test.pdf')

In [ ]:
!mkdir pages

In [ ]:
for i in range(len(images)):
  images[i].save('pages/page'+str(i)+'.jpg', 'JPEG')

# Layout

## Installation

In [1]:
#!python3 -m pip install paddlepaddle-gpu
!pip install "paddleocr>=2.0.1"
!pip install protobuf==3.20.0
!git clone https://github.com/PaddlePaddle/PaddleOCR.git

fatal: destination path 'PaddleOCR' already exists and is not an empty directory.


In [4]:
a=5

In [2]:
!wget https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
!pip install -U layoutparser-0.0.0-py3-none-any.whl

--2024-04-01 05:41:28--  https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
Resolving paddleocr.bj.bcebos.com (paddleocr.bj.bcebos.com)... 103.235.46.61, 2409:8c04:1001:1203:0:ff:b0bb:4f27
Connecting to paddleocr.bj.bcebos.com (paddleocr.bj.bcebos.com)|103.235.46.61|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19145360 (18M) [application/octet-stream]
Saving to: ‘layoutparser-0.0.0-py3-none-any.whl.2’

layoutparser-0.0.0- 100%[===================>]  18.26M  4.90MB/s    in 18s     

2024-04-01 05:41:48 (1.01 MB/s) - ‘layoutparser-0.0.0-py3-none-any.whl.2’ saved [19145360/19145360]

Processing ./layoutparser-0.0.0-py3-none-any.whl
layoutparser is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.


## Table Extraction

In [12]:

!pip uninstall layoutparser

Found existing installation: layoutparser 0.3.4
Uninstalling layoutparser-0.3.4:
  Would remove:
    /usr/local/lib/python3.10/dist-packages/layoutparser-0.3.4.dist-info/*
    /usr/local/lib/python3.10/dist-packages/layoutparser/*
Proceed (Y/n)? Y
  Successfully uninstalled layoutparser-0.3.4


In [26]:
import cv2
import layoutparser as lp
image = cv2.imread("/content/pages/page14.jpg")

image = image[..., ::-1]

# load model
model = lp.PaddleDetectionLayoutModel(config_path="lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config",
                                threshold=0.5,
                                label_map={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"},
                                enforce_cpu=False,
                                enable_mkldnn=True)#math kernel library
# detect
layout = model.detect(image)

In [27]:
layout

Layout(_blocks=[TextBlock(block=Rectangle(x_1=849.2144775390625, y_1=182.25164794921875, x_2=1552.0179443359375, y_2=767.7262573242188), text=None, id=None, type=Text, parent=None, next=None, score=0.9796910285949707), TextBlock(block=Rectangle(x_1=136.03067016601562, y_1=181.22137451171875, x_2=805.658935546875, y_2=938.2108764648438), text=None, id=None, type=List, parent=None, next=None, score=0.9715542793273926), TextBlock(block=Rectangle(x_1=105.449462890625, y_1=1036.938720703125, x_2=801.5697021484375, y_2=1092.966064453125), text=None, id=None, type=Text, parent=None, next=None, score=0.9526569843292236), TextBlock(block=Rectangle(x_1=103.62726593017578, y_1=981.725341796875, x_2=335.8999328613281, y_2=1007.0205078125), text=None, id=None, type=Title, parent=None, next=None, score=0.9222990870475769), TextBlock(block=Rectangle(x_1=102.9405746459961, y_1=1121.4371337890625, x_2=166.167236328125, y_2=1143.9862060546875), text=None, id=None, type=Title, parent=None, next=None, sco

In [28]:
x_1=0
y_1=0
x_2=0
y_2=0

for l in layout:
  #print(l)
  if l.type == 'Table':
    x_1 = int(l.block.x_1)
    print(l.block.x_1)
    y_1 = int(l.block.y_1)
    x_2 = int(l.block.x_2)
    y_2 = int(l.block.y_2)

    break

103.75275


In [29]:
print(x_1,y_1,x_2,y_2)

103 1179 1545 1469


In [30]:
im = cv2.imread('/content/pages/page14.jpg')

In [31]:
cv2.imwrite('ext_im.jpg', im[y_1:y_2,x_1:x_2])

True

# Text Detection and Recognition

In [33]:
from paddleocr import PaddleOCR, draw_ocr

In [34]:
ocr = PaddleOCR(lang='en')
image_path = '/content/ext_im.jpg'
image_cv = cv2.imread(image_path)
image_height = image_cv.shape[0]
image_width = image_cv.shape[1]
output = ocr.ocr(image_path)[0]

[2024/04/01 06:58:00] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/en/en_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='

In [35]:
print(output)

[[[[22.0, 4.0], [120.0, 8.0], [120.0, 34.0], [21.0, 30.0]], ('References', 0.9957192540168762)], [[[427.0, 8.0], [470.0, 8.0], [470.0, 32.0], [427.0, 32.0]], ('MSE', 0.9979258179664612)], [[[664.0, 9.0], [718.0, 9.0], [718.0, 32.0], [664.0, 32.0]], ('RMSE', 0.9967516660690308)], [[[898.0, 8.0], [948.0, 8.0], [948.0, 33.0], [898.0, 33.0]], ('MAE', 0.9972245097160339)], [[[1134.0, 6.0], [1194.0, 6.0], [1194.0, 33.0], [1134.0, 33.0]], ('MAPE', 0.9948724508285522)], [[[1370.0, 3.0], [1401.0, 3.0], [1401.0, 35.0], [1370.0, 35.0]], ('R2', 0.9919352531433105)], [[[24.0, 45.0], [192.0, 45.0], [192.0, 66.0], [24.0, 66.0]], ('Nayak et al.,2012', 0.9597781896591187)], [[[1136.0, 44.0], [1199.0, 44.0], [1199.0, 66.0], [1136.0, 66.0]], ('4.4130', 0.9988265037536621)], [[[24.0, 69.0], [167.0, 69.0], [167.0, 91.0], [24.0, 91.0]], ('Liu et al.2018', 0.971381664276123)], [[[428.0, 68.0], [490.0, 68.0], [490.0, 91.0], [428.0, 91.0]], ('1.0600', 0.9987771511077881)], [[[664.0, 68.0], [726.0, 68.0], [726.

In [36]:
boxes = [line[0] for line in output]
texts = [line[1][0] for line in output]
probabilities = [line[1][1] for line in output]

In [37]:
image_boxes = image_cv.copy()


In [38]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes, (int(box[0][0]),int(box[0][1])), (int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes, text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [39]:
cv2.imwrite('detections.jpg', image_boxes)

True

# Reconstruction

## Get Horizontal and Vertical Lines

In [40]:
im = image_cv.copy()

In [41]:
horiz_boxes = []
vert_boxes = []

for box in boxes:
  x_h, x_v = 0,int(box[0][0])
  y_h, y_v = int(box[0][1]),0
  width_h,width_v = image_width, int(box[2][0]-box[0][0])
  height_h,height_v = int(box[2][1]-box[0][1]),image_height

  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h), (x_h+width_h,y_h+height_h),(0,0,255),1)
  cv2.rectangle(im,(x_v,y_v), (x_v+width_v,y_v+height_v),(0,255,0),1)


In [42]:
cv2.imwrite('horiz_vert.jpg',im)

True

## Non-Max Suppression

In [45]:
horiz_out = tf.image.non_max_suppression(
    horiz_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [46]:
horiz_lines = np.sort(np.array(horiz_out))
print(horiz_lines)

[ 1  7 10 13 16 19 26 28 31 35 38]


In [47]:
im_nms = image_cv.copy()

In [48]:
for val in horiz_lines:
  cv2.rectangle(im_nms, (int(horiz_boxes[val][0]),int(horiz_boxes[val][1])), (int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)


In [49]:
cv2.imwrite('im_nms.jpg',im_nms)

True

In [50]:
vert_out = tf.image.non_max_suppression(
    vert_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [51]:
print(vert_out)

tf.Tensor([31 13 38 26 32  0], shape=(6,), dtype=int32)


In [52]:
vert_lines = np.sort(np.array(vert_out))
print(vert_lines)

[ 0 13 26 31 32 38]


In [53]:
for val in vert_lines:
  cv2.rectangle(im_nms, (int(vert_boxes[val][0]),int(vert_boxes[val][1])), (int(vert_boxes[val][2]),int(vert_boxes[val][3])),(255,0,0),1)


In [54]:
cv2.imwrite('im_nms.jpg',im_nms)

True

## Convert to CSV

In [55]:


out_array = [["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(np.array(out_array).shape)
print(out_array)

(11, 6)
[['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']]


In [56]:

unordered_boxes = []

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[22, 0, 120, 290]
[427, 0, 490, 290]
[900, 0, 963, 290]
[660, 0, 728, 290]
[1136, 0, 1200, 290]
[1371, 0, 1427, 290]


In [57]:
ordered_boxes = np.argsort(unordered_boxes)
print(ordered_boxes)

[0 1 3 2 4 5]


In [58]:
def intersection(box_1, box_2):
  return [box_2[0], box_1[1],box_2[2], box_1[3]]

In [59]:
def iou(box_1, box_2):

  x_1 = max(box_1[0], box_2[0])
  y_1 = max(box_1[1], box_2[1])
  x_2 = min(box_1[2], box_2[2])
  y_2 = min(box_1[3], box_2[3])

  inter = abs(max((x_2 - x_1, 0)) * max((y_2 - y_1), 0))
  if inter == 0:
      return 0

  box_1_area = abs((box_1[2] - box_1[0]) * (box_1[3] - box_1[1]))
  box_2_area = abs((box_2[2] - box_2[0]) * (box_2[3] - box_2[1]))

  return inter / float(box_1_area + box_2_area - inter)

In [60]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant = intersection(horiz_boxes[horiz_lines[i]], vert_boxes[vert_lines[ordered_boxes[j]]] )

    for b in range(len(boxes)):
      the_box = [boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if(iou(resultant,the_box)>0.1):
        out_array[i][j] = texts[b]

In [61]:
out_array=np.array(out_array)

In [62]:
out_array

array([['References', 'MSE', 'RMSE', 'MAE', 'MAPE', 'R2'],
       ['Nayak et al.,2012', '', '', '', '4.4130', ''],
       ['Liu et al.2018', '1.0600', '1.0296', '', '', '99.6'],
       ['Abhishek et al.2012', '2.7100', '1.6460', '', '', ''],
       ['(Suksri and Kimpan,2016)', '0.0212', '0.1476', '', '', ''],
       ['Yu et al.2016', '0.0281', '0.1676', '0.1062', '0.0279', ''],
       ['Rasel et al.2017', '10.956', '3.3100', '2.2900', '', ''],
       ['Ahmed,2015', '', '', '', '', '93.36'],
       ['Mohammadi et al.,2015', '0.4501', '0.6709', '', '0.5203',
        '98.77'],
       ['Hossain et al.,2015', '1.9044', '1.3800', '', '', ''],
       ['Liu et al.2015', '', '', '', '', '91.50']], dtype='<U24')

In [63]:
pd.DataFrame(out_array).to_csv('sample.csv')

## Merging Cells

In [ ]:
current_bank=['']*len(out_array[0,:])
print(current_bank)

['', '', '', '', '', '', '']


In [ ]:
def empty(arr):
  for i in arr:
    if i=='':
      return True
  return False

In [ ]:
cleaned_array=[]

In [ ]:
for i in range(len(out_array)):
  if not empty(out_array[i]):
    current_bank=[out_array[i][j] for j in range(len(out_array[i]))]
    cleaned_array.append(current_bank)
    not_empty=True
  else:
    for j in range(len(out_array[i])):
      current_bank[j]+=' '+out_array[i][j]
    print('-->',current_bank)
cleaned_array=np.array(cleaned_array)
print(cleaned_array)

[['Model' 'Updates (105)' 'Epochs' 'Hours' 'GPU' 'Train NLL' 'Dev.NLL']
 ['RNNenc-30' '8.46' '6.4' '109' 'TITAN BLACK' '28.1' '53.0']
 ['RNNenc-50' '6.00' '4.5' '108' 'Quadro K-6000' '44.0' '43.6']
 ['RNNsearch-30' '4.71' '3.6' '113' 'TITAN BLACK' '26.7' '47.2']
 ['RNNsearch-50' '2.88' '2.2' '111' 'Quadro K-6000' '40.7' '38.1']
 ['RNNsearch-50*' '6.67' '5.0' '252' 'Quadro K-6000' '36.7' '35.2']]


In [ ]:
pd.DataFrame(cleaned_array).to_csv('cleaned.csv')

# Convert to OWL Format

# **CSV to Text**

In [ ]:
import  jpype
import  asposecells


jpype.startJVM()
from asposecells.api import Workbook

workbook = Workbook("/content/sample.csv")
workbook.save("Output.docx")
jpype.shutdownJVM()

ModuleNotFoundError: ignored

# Brighten Image (For Anyone dealing with PDFs created from scanned images)

In [ ]:
from PIL import Image, ImageEnhance

#read the image
im = Image.open("ext_im.jpg")

#image brightness enhancer
enhancer = ImageEnhance.Brightness(im)

factor = 1 #gives original image
im_output = enhancer.enhance(factor)
im_output.save('ext_im-1.jpg')

factor = 1.5## brightens the image
im_output = enhancer.enhance(factor)
im_output.save('ext_im-2.jpg')
